In [1]:
import dateutil
import datetime
import numpy as np
import pandas as pd

In [2]:
fips = pd.read_csv('/Users/alexy161/Downloads/all-geocodes-v2016.csv')
fips.columns=['summary', 'state', 'county', 'sub', 'place', 'city', 'name']
fips = fips[fips.summary == 50]
fips['code'] = fips.state*1000 + fips.county
vafips = fips[fips.state == 51]
vafips = vafips[['name', 'code']]

In [23]:
listing = pd.read_csv('/Users/alexy161/Downloads/County/County_MedianListingPrice_AllHomes.csv',encoding='latin1')
listing = pd.melt(listing, id_vars=['StateCodeFIPS','MunicipalCodeFIPS'], value_vars=['2010-01', '2010-02', '2010-03',
       '2010-04', '2010-05', '2010-06', '2010-07', '2010-08', '2010-09',
       '2010-10', '2010-11', '2010-12', '2011-01', '2011-02', '2011-03',
       '2011-04', '2011-05', '2011-06', '2011-07', '2011-08', '2011-09',
       '2011-10', '2011-11', '2011-12', '2012-01', '2012-02', '2012-03',
       '2012-04', '2012-05', '2012-06', '2012-07', '2012-08', '2012-09',
       '2012-10', '2012-11', '2012-12', '2013-01', '2013-02', '2013-03',
       '2013-04', '2013-05', '2013-06', '2013-07', '2013-08', '2013-09',
       '2013-10', '2013-11', '2013-12', '2014-01', '2014-02', '2014-03',
       '2014-04', '2014-05', '2014-06', '2014-07', '2014-08', '2014-09',
       '2014-10', '2014-11', '2014-12', '2015-01', '2015-02', '2015-03',
       '2015-04', '2015-05', '2015-06', '2015-07', '2015-08', '2015-09',
       '2015-10', '2015-11', '2015-12', '2016-01', '2016-02', '2016-03',
       '2016-04', '2016-05', '2016-06', '2016-07', '2016-08', '2016-09',
       '2016-10', '2016-11', '2016-12', '2017-01', '2017-02', '2017-03',
       '2017-04', '2017-05', '2017-06', '2017-07', '2017-08', '2017-09',
       '2017-10', '2017-11', '2017-12', '2018-01', '2018-02', '2018-03',
       '2018-04', '2018-05', '2018-06', '2018-07', '2018-08', '2018-09',
       '2018-10'], var_name = 'date', value_name = 'price')
listing['FIPS'] = 1000*listing.StateCodeFIPS + listing.MunicipalCodeFIPS
listing = listing[['FIPS', 'date', 'price']]
fipsmin = listing['FIPS']>51000
fipsmax = listing['FIPS']<52000
listingva = listing[fipsmin & fipsmax]
listingva.date = listingva.date.apply(dateutil.parser.parse)
listingva.date = pd.to_datetime(listingva.date).map(lambda dt: dt.replace(day=1))
listingva = listingva.sort_values(by=['FIPS', 'date'])
listingva['prev_price_change'] = listingva.groupby(by=['FIPS'])['price'].pct_change(periods=12)*100
listingva1 = listingva[['FIPS', 'date', 'prev_price_change']]
listingva1.date = listingva1.date.apply(lambda x: x - pd.DateOffset(months=12))
listingva1.columns = ['FIPS', 'date', 'future_price_change']
listing = pd.merge(listingva, listingva1, on=['FIPS', 'date'])
listing.dropna()
listing

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

        FIPS       date     price  prev_price_change  future_price_change
0      51001 2010-01-01  219450.0                NaN           -12.280702
1      51001 2010-02-01  214900.0                NaN           -12.052117
2      51001 2010-03-01  219000.0                NaN           -13.287671
3      51001 2010-04-01  224900.0                NaN           -11.738550
4      51001 2010-05-01  224000.0                NaN           -11.160714
5      51001 2010-06-01  204200.0                NaN            -7.002938
6      51001 2010-07-01  215000.0                NaN           -12.093023
7      51001 2010-08-01  215000.0                NaN           -11.883721
8      51001 2010-09-01  218000.0                NaN           -13.302752
9      51001 2010-10-01  212000.0                NaN           -15.566038
10     51001 2010-11-01  199000.0                NaN           -11.356784
11     51001 2010-12-01  199750.0                NaN           -12.390488
12     51001 2011-01-01  192500.0         -12.280702            -9.922078
13     51001 2011-02-01  189000.0         -12.052117            -7.407407
14     51001 2011-03-01  189900.0         -13.287671            -7.846235
15     51001 2011-04-01  198500.0         -11.738550           -10.327456
16     51001 2011-05-01  199000.0         -11.160714           -12.060302
17     51001 2011-06-01  189900.0          -7.002938            -6.319115
18     51001 2011-07-01  189000.0         -12.093023            -5.291005
19     51001 2011-08-01  189450.0         -11.883721            -7.627342
20     51001 2011-09-01  189000.0         -13.302752            -7.460317
21     51001 2011-10-01  179000.0         -15.566038            -5.179888
22     51001 2011-11-01  176400.0         -11.356784            -3.684807
23     51001 2011-12-01  175000.0         -12.390488            -3.428571
24     51001 2012-01-01  173400.0          -9.922078            -3.114187
25     51001 2012-02-01  175000.0          -7.407407            -8.628571
26     51001 2012-03-01  175000.0          -7.846235            -8.628571
27     51001 2012-04-01  178000.0         -10.327456           -10.117978
28     51001 2012-05-01  175000.0         -12.060302            -4.000000
29     51001 2012-06-01  177900.0          -6.319115            -5.002811
...      ...        ...       ...                ...                  ...
11062  51840 2015-05-01  259900.0           8.744770            21.950750
11063  51840 2015-06-01  259500.0          10.004239            22.138728
11064  51840 2015-07-01  244900.0           2.468619            30.665578
11065  51840 2015-08-01  249250.0           6.063830            25.175527
11066  51840 2015-09-01  249900.0          12.352478            20.048019
11067  51840 2015-10-01  249900.0           5.443038            17.226891
11068  51840 2015-11-01  249450.0           3.980825            19.422730
11069  51840 2015-12-01  249900.0           9.126638            21.548619
11070  51840 2016-01-01  249900.0           8.912617            20.008003
11071  51840 2016-02-01  253000.0          10.047847            10.454545
11072  51840 2016-03-01  249900.0           2.903027             9.823930
11073  51840 2016-04-01  279900.0          12.004802             6.198642
11074  51840 2016-05-01  316950.0          21.950750            -6.152390
11075  51840 2016-06-01  316950.0          22.138728           -17.210917
11076  51840 2016-07-01  320000.0          30.665578           -12.359375
11077  51840 2016-08-01  312000.0          25.175527           -10.769231
11078  51840 2016-09-01  300000.0          20.048019           -10.166667
11079  51840 2016-10-01  292950.0          17.226891           -14.695341
11080  51840 2016-11-01  297900.0          19.422730           -17.086271
11081  51840 2016-12-01  303750.0          21.548619           -21.020576
11082  51840 2017-01-01  299900.0          20.008003           -16.672224
11083  51840 2017-02-01  279450.0          10.454545            -1.628198
11084  51840 2017-03-01  274450.0           9.823930             7.487703
11085  51840 2017-04-01  297250.0           6.198642            -0.756939
11086  51840 2017-05-01  297450.0          -6.152390            -3.698101
11087  51840 2017-06-01  262400.0         -17.210917            10.041921
11088  51840 2017-07-01  280450.0         -12.359375            -2.852558
11089  51840 2017-08-01  278400.0         -10.769231             6.681034
11090  51840 2017-09-01  269500.0         -10.166667            -1.669759
11091  51840 2017-10-01  249900.0         -14.695341             3.821529

[11092 rows x 5 columns]

In [4]:
rent = pd.read_csv('/Users/alexy161/Downloads/County/County_MedianRentalPrice_AllHomes.csv',encoding='latin1')
rent = pd.melt(rent, id_vars=['StateCodeFIPS','MunicipalCodeFIPS'], value_vars=['2010-01', '2010-02', '2010-03',
       '2010-04', '2010-05', '2010-06', '2010-07', '2010-08', '2010-09',
       '2010-10', '2010-11', '2010-12', '2011-01', '2011-02', '2011-03',
       '2011-04', '2011-05', '2011-06', '2011-07', '2011-08', '2011-09',
       '2011-10', '2011-11', '2011-12', '2012-01', '2012-02', '2012-03',
       '2012-04', '2012-05', '2012-06', '2012-07', '2012-08', '2012-09',
       '2012-10', '2012-11', '2012-12', '2013-01', '2013-02', '2013-03',
       '2013-04', '2013-05', '2013-06', '2013-07', '2013-08', '2013-09',
       '2013-10', '2013-11', '2013-12', '2014-01', '2014-02', '2014-03',
       '2014-04', '2014-05', '2014-06', '2014-07', '2014-08', '2014-09',
       '2014-10', '2014-11', '2014-12', '2015-01', '2015-02', '2015-03',
       '2015-04', '2015-05', '2015-06', '2015-07', '2015-08', '2015-09',
       '2015-10', '2015-11', '2015-12', '2016-01', '2016-02', '2016-03',
       '2016-04', '2016-05', '2016-06', '2016-07', '2016-08', '2016-09',
       '2016-10', '2016-11', '2016-12', '2017-01', '2017-02', '2017-03',
       '2017-04', '2017-05', '2017-06', '2017-07', '2017-08', '2017-09',
       '2017-10', '2017-11', '2017-12', '2018-01', '2018-02', '2018-03',
       '2018-04', '2018-05', '2018-06', '2018-07', '2018-08', '2018-09',
       '2018-10'])
rent['FIPS'] = 1000*rent.StateCodeFIPS + rent.MunicipalCodeFIPS
rent = rent[['FIPS', 'variable', 'value']]
rent.columns=['FIPS', 'date', 'rent']
fipsmin = rent['FIPS']>51000
fipsmax = rent['FIPS']<52000
rentva = rent[fipsmin & fipsmax]
rentva.date = rentva.date.apply(dateutil.parser.parse)
rentva.date = pd.to_datetime(rentva.date).map(lambda dt: dt.replace(day=1))
rentva = rentva.sort_values(by=['FIPS', 'date'])
rentva1 = rentva[['FIPS', 'date', 'rent']]
rentva1['rent_change'] = rentva.groupby(by=['FIPS'])['rent'].diff(periods=12)
rentva1.date = rentva1.date.apply(lambda x: x - pd.DateOffset(months=12))
rentva1 = rentva1[['FIPS', 'date', 'rent_change']]
rent = pd.merge(rentva, rentva1, on=['FIPS', 'date'])
rent.price_change = rent.rent_change/rent.rent

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:35: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access

In [5]:
unemp1 = pd.read_csv('/Users/alexy161/Downloads/la.data.0.CurrentU10-14.txt', delimiter = '\t')
unemp2 = pd.read_csv('/Users/alexy161/Downloads/la.data.0.CurrentU15-19.txt', delimiter = '\t')
unframes = [unemp1, unemp2]
unemp = pd.concat(unframes)
unemp.series_id = unemp.series_id.str.strip()
unemp = unemp[unemp['series_id'].str.contains('LAUCN')]
unemp = unemp[unemp['series_id'].str.endswith('3')]
unemp.series_id = unemp.series_id.str[5:]
unemp.series_id = unemp.series_id.str[:5]
unemp = unemp.drop('footnote_codes', axis=1)
unemp = unemp[unemp.period != 'M13']
unemp.period = unemp.period.str[1:]
unemp['date'] = unemp['year'].astype(str) + '-' + unemp['period']
unemp = unemp.sort_values(by=['series_id', 'date']).reset_index()
unemp.date = unemp.date.apply(dateutil.parser.parse)
unemp.date = unemp.date.map(lambda dt: dt.replace(day=1))
unemp['annual_unemp_change'] = unemp.groupby(by=['series_id'])['value'].diff(periods=12)
unemp = unemp.rename({'value': 'unemp_rate'}, axis=1)
unemp = unemp[['series_id', 'date', 'unemp_rate', 'annual_unemp_change']]
unemp.series_id = unemp.series_id.astype(int)
unemp = unemp.dropna()

In [6]:
fore = pd.read_csv('/Users/alexy161/Downloads/County/ForeclosuresPer10Khomes_County.csv')
fore = pd.melt(fore, id_vars=['RegionID'], value_vars=['2008-01',
       '2008-02', '2008-03', '2008-04', '2008-05', '2008-06', '2008-07',
       '2008-08', '2008-09', '2008-10', '2008-11', '2008-12', '2009-01',
       '2009-02', '2009-03', '2009-04', '2009-05', '2009-06', '2009-07',
       '2009-08', '2009-09', '2009-10', '2009-11', '2009-12', '2010-01',
       '2010-02', '2010-03', '2010-04', '2010-05', '2010-06', '2010-07',
       '2010-08', '2010-09', '2010-10', '2010-11', '2010-12', '2011-01',
       '2011-02', '2011-03', '2011-04', '2011-05', '2011-06', '2011-07',
       '2011-08', '2011-09', '2011-10', '2011-11', '2011-12', '2012-01',
       '2012-02', '2012-03', '2012-04', '2012-05', '2012-06', '2012-07',
       '2012-08', '2012-09', '2012-10', '2012-11', '2012-12', '2013-01',
       '2013-02', '2013-03', '2013-04', '2013-05', '2013-06', '2013-07',
       '2013-08', '2013-09', '2013-10', '2013-11', '2013-12', '2014-01',
       '2014-02', '2014-03', '2014-04', '2014-05', '2014-06', '2014-07',
       '2014-08', '2014-09', '2014-10', '2014-11', '2014-12', '2015-01',
       '2015-02', '2015-03', '2015-04', '2015-05', '2015-06', '2015-07',
       '2015-08', '2015-09', '2015-10', '2015-11', '2015-12', '2016-01',
       '2016-02', '2016-03', '2016-04', '2016-05', '2016-06', '2016-07',
       '2016-08', '2016-09', '2016-10', '2016-11', '2016-12', '2017-01',
       '2017-02', '2017-03', '2017-04', '2017-05', '2017-06', '2017-07',
       '2017-08', '2017-09', '2017-10', '2017-11', '2017-12', '2018-01',
       '2018-02', '2018-03', '2018-04', '2018-05', '2018-06', '2018-07',
       '2018-08', '2018-09', '2018-10'])
crosswalk = pd.read_csv('/Users/alexy161/Downloads/zecon/CountyCrossWalk_Zillow.csv')
cross = crosswalk[['CountyRegionID_Zillow', 'FIPS']]
foreclose = pd.merge(fore, crosswalk, left_on='RegionID', right_on='CountyRegionID_Zillow')
foreclose = foreclose[['FIPS', 'variable', 'value']]
foreclose.columns = ['FIPS', 'date', 'foreclose_rate']
foreclose = foreclose.dropna()
foreclose.date = foreclose.date.apply(dateutil.parser.parse)
foreclose.date = pd.to_datetime(foreclose.date).map(lambda dt: dt.replace(day=1))
foreclose = foreclose.sort_values(by=['FIPS', 'date'])
foreclose['foreclose_rate_change'] = foreclose.foreclose_rate.rolling(window=12).mean()
foreclose = foreclose.dropna()

In [7]:
popul = pd.read_csv('/Users/alexy161/Downloads/PEP_2017_PEPANNRES/PEP_2017_PEPANNRES_with_ann.csv', encoding='latin1')
popul.drop(popul.index[0],inplace=True)
popul = popul[['GEO.id2', 'respop72010', 'respop72011', 'respop72012', 'respop72013', 'respop72014', 'respop72015', 'respop72016', 'respop72017']]
popul.columns = ['FIPS', '2010-07', '2011-07', '2012-07', '2013-07', '2014-07', '2015-07', '2016-07', '2017-07']
popul['2010-08'] = popul['2010-07']
popul['2010-09'] = popul['2010-07']
popul['2010-10'] = popul['2010-07']
popul['2010-11'] = popul['2010-07']
popul['2010-12'] = popul['2010-07']
popul['2011-01'] = popul['2010-07']
popul['2011-02'] = popul['2010-07']
popul['2011-03'] = popul['2010-07']
popul['2011-04'] = popul['2010-07']
popul['2011-05'] = popul['2010-07']
popul['2011-06'] = popul['2010-07']
popul['2011-08'] = popul['2011-07']
popul['2011-09'] = popul['2011-07']
popul['2011-10'] = popul['2011-07']
popul['2011-11'] = popul['2011-07']
popul['2011-12'] = popul['2011-07']
popul['2012-01'] = popul['2011-07']
popul['2012-02'] = popul['2011-07']
popul['2012-03'] = popul['2011-07']
popul['2012-04'] = popul['2011-07']
popul['2012-05'] = popul['2011-07']
popul['2012-06'] = popul['2011-07']
popul['2012-08'] = popul['2012-07']
popul['2012-09'] = popul['2012-07']
popul['2012-10'] = popul['2012-07']
popul['2012-11'] = popul['2012-07']
popul['2012-12'] = popul['2012-07']
popul['2013-01'] = popul['2012-07']
popul['2013-02'] = popul['2012-07']
popul['2013-03'] = popul['2012-07']
popul['2013-04'] = popul['2012-07']
popul['2013-05'] = popul['2012-07']
popul['2013-06'] = popul['2012-07']
popul['2013-08'] = popul['2013-07']
popul['2013-09'] = popul['2013-07']
popul['2013-10'] = popul['2013-07']
popul['2013-11'] = popul['2013-07']
popul['2013-12'] = popul['2013-07']
popul['2014-01'] = popul['2013-07']
popul['2014-02'] = popul['2013-07']
popul['2014-03'] = popul['2013-07']
popul['2014-04'] = popul['2013-07']
popul['2014-05'] = popul['2013-07']
popul['2014-06'] = popul['2013-07']
popul['2014-08'] = popul['2014-07']
popul['2014-09'] = popul['2014-07']
popul['2014-10'] = popul['2014-07']
popul['2014-11'] = popul['2014-07']
popul['2014-12'] = popul['2014-07']
popul['2015-01'] = popul['2014-07']
popul['2015-02'] = popul['2014-07']
popul['2015-03'] = popul['2014-07']
popul['2015-04'] = popul['2014-07']
popul['2015-05'] = popul['2014-07']
popul['2015-06'] = popul['2014-07']
popul['2015-08'] = popul['2015-07']
popul['2015-09'] = popul['2015-07']
popul['2015-10'] = popul['2015-07']
popul['2015-11'] = popul['2015-07']
popul['2015-12'] = popul['2015-07']
popul['2016-01'] = popul['2015-07']
popul['2016-02'] = popul['2015-07']
popul['2016-03'] = popul['2015-07']
popul['2016-04'] = popul['2015-07']
popul['2016-05'] = popul['2015-07']
popul['2016-06'] = popul['2015-07']
popul['2016-08'] = popul['2016-07']
popul['2016-09'] = popul['2016-07']
popul['2016-10'] = popul['2016-07']
popul['2016-11'] = popul['2016-07']
popul['2016-12'] = popul['2016-07']
popul['2017-01'] = popul['2016-07']
popul['2017-02'] = popul['2016-07']
popul['2017-03'] = popul['2016-07']
popul['2017-04'] = popul['2016-07']
popul['2017-05'] = popul['2016-07']
popul['2017-06'] = popul['2016-07']
popul['2017-08'] = popul['2017-07']
popul['2017-09'] = popul['2017-07']
popul['2017-10'] = popul['2017-07']
popul['2017-11'] = popul['2017-07']
popul['2017-12'] = popul['2017-07']
popul['2018-01'] = popul['2017-07']
popul['2018-02'] = popul['2017-07']
popul['2018-03'] = popul['2017-07']
popul['2018-04'] = popul['2017-07']
popul['2018-05'] = popul['2017-07']
popul['2018-06'] = popul['2017-07']
popul = pd.melt(popul, id_vars = ['FIPS'], value_vars=['2010-07', '2011-07', '2012-07', '2013-07', '2014-07',
       '2015-07', '2016-07', '2017-07', '2010-08', '2010-09', '2010-10',
       '2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-08', '2011-09', '2011-10', '2011-11',
       '2011-12', '2012-01', '2012-02', '2012-03', '2012-04', '2012-05',
       '2012-06', '2012-08', '2012-09', '2012-10', '2012-11', '2012-12',
       '2013-01', '2013-02', '2013-03', '2013-04', '2013-05', '2013-06',
       '2013-08', '2013-09', '2013-10', '2013-11', '2013-12', '2014-01',
       '2014-02', '2014-03', '2014-04', '2014-05', '2014-06', '2014-08',
       '2014-09', '2014-10', '2014-11', '2014-12', '2015-01', '2015-02',
       '2015-03', '2015-04', '2015-05', '2015-06', '2015-08', '2015-09',
       '2015-10', '2015-11', '2015-12', '2016-01', '2016-02', '2016-03',
       '2016-04', '2016-05', '2016-06', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-08', '2017-09', '2017-10', '2017-11',
       '2017-12', '2018-01', '2018-02', '2018-03', '2018-04', '2018-05',
       '2018-06'])
popul.columns = ['FIPS', 'date', 'popul']
popul.date = popul.date.apply(dateutil.parser.parse)
popul.date = pd.to_datetime(popul.date).map(lambda dt: dt.replace(day=1))
popul.popul = popul.popul.astype(int)
popul = popul.sort_values(by=['FIPS', 'date']).reset_index()
popul['annual_popul_change'] = popul.groupby(by=['FIPS'])['popul'].pct_change(periods=12)
popul = popul[['FIPS', 'date', 'popul', 'annual_popul_change']]
popul.FIPS = popul.FIPS.astype(int)

In [8]:
inven = pd.read_csv('/Users/alexy161/Downloads/County/InventoryMeasure_County_Public.csv', encoding='latin1')
inven = pd.melt(inven, id_vars=['CountyName', 'StateFullName'], value_vars=['2010-01', '2010-02', '2010-03', '2010-04',
       '2010-05', '2010-06', '2010-07', '2010-08', '2010-09', '2010-10',
       '2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-07', '2011-08', '2011-09', '2011-10',
       '2011-11', '2011-12', '2012-01', '2012-02', '2012-03', '2012-04',
       '2012-05', '2012-06', '2012-07', '2012-08', '2012-09', '2012-10',
       '2012-11', '2012-12', '2013-01', '2013-02', '2013-03', '2013-04',
       '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10',
       '2013-11', '2013-12', '2014-01', '2014-02', '2014-03', '2014-04',
       '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10',
       '2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04',
       '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10',
       '2015-11', '2015-12', '2016-01', '2016-02', '2016-03', '2016-04',
       '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10',
       '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04',
       '2018-05', '2018-06', '2018-07', '2018-08', '2018-09'], var_name = 'month', value_name = 'inven')
cross2 = crosswalk[['CountyName', 'StateName', 'FIPS']]
inventory = pd.merge(inven, cross2, left_on = ['CountyName', 'StateFullName'], right_on = ['CountyName', 'StateName'])
inventory = inventory[['FIPS', 'month', 'inven']]
inventory = inventory.sort_values(by=['FIPS', 'month'])
inventory.month = inventory.month.apply(dateutil.parser.parse)
inventory.month = pd.to_datetime(inventory.month).map(lambda dt: dt.replace(day=1))
inventory['inven_change'] = inventory.groupby(by=['FIPS'])['inven'].pct_change(periods=12)

In [9]:
inc = pd.read_csv('/Users/alexy161/Downloads/personal_income.csv', encoding='latin1')
inc.GeoFIPS = inc.GeoFIPS.str.strip()
inc.GeoFIPS = inc.GeoFIPS.str[1:6]
inc.GeoFIPS = inc.GeoFIPS.astype(int)
inc.columns = ['FIPS', 'GeoName', 'Region', 'TableName', 'LineCode',
       'IndustryClassification', 'Description', 'Unit', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010-07',
       '2011-07', '2012-07', '2013-07', '2014-07', '2015-07', '2016-07', '2017-07']
inc['2010-08'] = inc['2010-07']
inc['2010-09'] = inc['2010-07']
inc['2010-10'] = inc['2010-07']
inc['2010-11'] = inc['2010-07']
inc['2010-12'] = inc['2010-07']
inc['2011-01'] = inc['2010-07']
inc['2011-02'] = inc['2010-07']
inc['2011-03'] = inc['2010-07']
inc['2011-04'] = inc['2010-07']
inc['2011-05'] = inc['2010-07']
inc['2011-06'] = inc['2010-07']
inc['2011-08'] = inc['2011-07']
inc['2011-09'] = inc['2011-07']
inc['2011-10'] = inc['2011-07']
inc['2011-11'] = inc['2011-07']
inc['2011-12'] = inc['2011-07']
inc['2012-01'] = inc['2011-07']
inc['2012-02'] = inc['2011-07']
inc['2012-03'] = inc['2011-07']
inc['2012-04'] = inc['2011-07']
inc['2012-05'] = inc['2011-07']
inc['2012-06'] = inc['2011-07']
inc['2012-08'] = inc['2012-07']
inc['2012-09'] = inc['2012-07']
inc['2012-10'] = inc['2012-07']
inc['2012-11'] = inc['2012-07']
inc['2012-12'] = inc['2012-07']
inc['2013-01'] = inc['2012-07']
inc['2013-02'] = inc['2012-07']
inc['2013-03'] = inc['2012-07']
inc['2013-04'] = inc['2012-07']
inc['2013-05'] = inc['2012-07']
inc['2013-06'] = inc['2012-07']
inc['2013-08'] = inc['2013-07']
inc['2013-09'] = inc['2013-07']
inc['2013-10'] = inc['2013-07']
inc['2013-11'] = inc['2013-07']
inc['2013-12'] = inc['2013-07']
inc['2014-01'] = inc['2013-07']
inc['2014-02'] = inc['2013-07']
inc['2014-03'] = inc['2013-07']
inc['2014-04'] = inc['2013-07']
inc['2014-05'] = inc['2013-07']
inc['2014-06'] = inc['2013-07']
inc['2014-08'] = inc['2014-07']
inc['2014-09'] = inc['2014-07']
inc['2014-10'] = inc['2014-07']
inc['2014-11'] = inc['2014-07']
inc['2014-12'] = inc['2014-07']
inc['2015-01'] = inc['2014-07']
inc['2015-02'] = inc['2014-07']
inc['2015-03'] = inc['2014-07']
inc['2015-04'] = inc['2014-07']
inc['2015-05'] = inc['2014-07']
inc['2015-06'] = inc['2014-07']
inc['2015-08'] = inc['2015-07']
inc['2015-09'] = inc['2015-07']
inc['2015-10'] = inc['2015-07']
inc['2015-11'] = inc['2015-07']
inc['2015-12'] = inc['2015-07']
inc['2016-01'] = inc['2015-07']
inc['2016-02'] = inc['2015-07']
inc['2016-03'] = inc['2015-07']
inc['2016-04'] = inc['2015-07']
inc['2016-05'] = inc['2015-07']
inc['2016-06'] = inc['2015-07']
inc['2016-08'] = inc['2016-07']
inc['2016-09'] = inc['2016-07']
inc['2016-10'] = inc['2016-07']
inc['2016-11'] = inc['2016-07']
inc['2016-12'] = inc['2016-07']
inc['2017-01'] = inc['2016-07']
inc['2017-02'] = inc['2016-07']
inc['2017-03'] = inc['2016-07']
inc['2017-04'] = inc['2016-07']
inc['2017-05'] = inc['2016-07']
inc['2017-06'] = inc['2016-07']
inc['2017-08'] = inc['2017-07']
inc['2017-09'] = inc['2017-07']
inc['2017-10'] = inc['2017-07']
inc['2017-11'] = inc['2017-07']
inc['2017-12'] = inc['2017-07']
inc['2018-01'] = inc['2017-07']
inc['2018-02'] = inc['2017-07']
inc['2018-03'] = inc['2017-07']
inc['2018-04'] = inc['2017-07']
inc['2018-05'] = inc['2017-07']
inc['2018-06'] = inc['2017-07']
inc_pc = inc[inc.LineCode == 30]
inc_pc = pd.melt(inc_pc, id_vars = ['FIPS'], value_vars=['2010-07', '2011-07', '2012-07', '2013-07', '2014-07',
       '2015-07', '2016-07', '2017-07', '2010-08', '2010-09', '2010-10',
       '2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-08', '2011-09', '2011-10', '2011-11',
       '2011-12', '2012-01', '2012-02', '2012-03', '2012-04', '2012-05',
       '2012-06', '2012-08', '2012-09', '2012-10', '2012-11', '2012-12',
       '2013-01', '2013-02', '2013-03', '2013-04', '2013-05', '2013-06',
       '2013-08', '2013-09', '2013-10', '2013-11', '2013-12', '2014-01',
       '2014-02', '2014-03', '2014-04', '2014-05', '2014-06', '2014-08',
       '2014-09', '2014-10', '2014-11', '2014-12', '2015-01', '2015-02',
       '2015-03', '2015-04', '2015-05', '2015-06', '2015-08', '2015-09',
       '2015-10', '2015-11', '2015-12', '2016-01', '2016-02', '2016-03',
       '2016-04', '2016-05', '2016-06', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-08', '2017-09', '2017-10', '2017-11',
       '2017-12', '2018-01', '2018-02', '2018-03', '2018-04', '2018-05',
       '2018-06'], var_name = 'date', value_name = 'inc_pc')
inc_pc = inc_pc.sort_values(by=['FIPS', 'date'])
inc_pc.date = inc_pc.date.apply(dateutil.parser.parse)
inc_pc.date = pd.to_datetime(inc_pc.date).map(lambda dt: dt.replace(day=1))
inc_pc = inc_pc[inc_pc.inc_pc != '(NA)']
inc_pc.inc_pc = inc_pc.inc_pc.astype(int)
inc_pc['inc_pc_change'] = inc_pc.groupby(by=['FIPS'])['inc_pc'].pct_change(periods=12)

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (2,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
total_emp = inc[inc.LineCode == 7020]
total_emp = pd.melt(total_emp, id_vars = ['FIPS'], value_vars=['2010-07', '2011-07', '2012-07', '2013-07', '2014-07',
       '2015-07', '2016-07', '2017-07', '2010-08', '2010-09', '2010-10',
       '2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-08', '2011-09', '2011-10', '2011-11',
       '2011-12', '2012-01', '2012-02', '2012-03', '2012-04', '2012-05',
       '2012-06', '2012-08', '2012-09', '2012-10', '2012-11', '2012-12',
       '2013-01', '2013-02', '2013-03', '2013-04', '2013-05', '2013-06',
       '2013-08', '2013-09', '2013-10', '2013-11', '2013-12', '2014-01',
       '2014-02', '2014-03', '2014-04', '2014-05', '2014-06', '2014-08',
       '2014-09', '2014-10', '2014-11', '2014-12', '2015-01', '2015-02',
       '2015-03', '2015-04', '2015-05', '2015-06', '2015-08', '2015-09',
       '2015-10', '2015-11', '2015-12', '2016-01', '2016-02', '2016-03',
       '2016-04', '2016-05', '2016-06', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-08', '2017-09', '2017-10', '2017-11',
       '2017-12', '2018-01', '2018-02', '2018-03', '2018-04', '2018-05',
       '2018-06'], var_name = 'date', value_name = 'total_emp')
total_emp = total_emp.sort_values(by=['FIPS', 'date'])
total_emp.date = total_emp.date.apply(dateutil.parser.parse)
total_emp.date = pd.to_datetime(total_emp.date).map(lambda dt: dt.replace(day=1))
total_emp = total_emp[total_emp.total_emp != '(NA)']
total_emp.total_emp = total_emp.total_emp.astype(int)
total_emp['emp_change'] = total_emp.groupby(by=['FIPS'])['total_emp'].pct_change(periods=12)

In [11]:
inf = pd.read_csv('/Users/alexy161/Downloads/DC_Area_Inflation.csv')
inf = pd.melt(inf, id_vars=['Year'], value_vars=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
       'Oct', 'Nov', 'Dec'], var_name = 'month', value_name = 'price_index')
inf = inf.dropna()
inf.Year = inf.Year.astype(str)
inf['timestamp'] = inf.Year + '-' + inf.month
inf.timestamp = inf.timestamp.apply(pd.to_datetime)
inf1 = inf[['timestamp', 'price_index']]
inf1 = inf1.sort_values(by='timestamp')
inf1['inf_diff'] = inf1.price_index.diff(periods=12)
inf1.timestamp = inf1.timestamp.apply(lambda x: x - pd.DateOffset(months=12))
inf1 = inf1[['timestamp', 'inf_diff']]
inf = pd.merge(inf, inf1, on=['timestamp'])
inf.inf_diff = inf.inf_diff/inf.price_index
inf = inf[['timestamp', 'inf_diff']]

In [12]:
vaa = pd.read_csv('/Users/alexy161/Downloads/AnnouncementsData.csv')
vaa.drop(vaa.index[2688:],inplace=True)
vaa.columns = ['company', 'county', 'NAICS', 'descript', 'date', 'new_expand', 'jobs_added', 'investment']
vaa.jobs_added = vaa.jobs_added.astype(int)
vaa.NAICS = vaa.NAICS.astype(int)
vaa.date = vaa.date.apply(dateutil.parser.parse)
vaa['month'] = pd.to_datetime(vaa['date']).map(lambda dt: dt.replace(day=1))
vaa['agriculture_added'] = np.where(vaa.NAICS < 100000, vaa.jobs_added, 0)
vaa['manufacturing_added'] = np.where((vaa.NAICS >= 100000) & (vaa.NAICS < 400000), vaa.jobs_added, 0)
vaa['service_added'] = np.where(vaa.NAICS >= 400000, vaa.jobs_added, 0)
vaa['new'] = np.where(vaa.new_expand == 'N', vaa.jobs_added, 0)
vaa['expansion'] = np.where(vaa.new_expand == 'E', vaa.jobs_added, 0)
vaa.NAICS = vaa.NAICS.astype(str)
vaa1 = vaa.groupby(by=['month', 'county']).sum().reset_index()
vac = pd.read_csv('/Users/alexy161/Downloads/ClosingData.csv')
vac.drop(vac.index[399:],inplace=True)
vac.columns = ['company', 'county', 'NAICS', 'descript', 'jobs_lost', 'close_layoff', 'date', 'month_close']
vac.jobs_lost = vac.jobs_lost.astype(int)
vac.NAICS = vac.NAICS.astype(int)
vac.date = vac.date.apply(dateutil.parser.parse)
vac['month'] = pd.to_datetime(vac['date']).map(lambda dt: dt.replace(day=1))
vac['agriculture_closed'] = np.where(vac.NAICS < 100000, vac.jobs_lost, 0)
vac['manufacturing_closed'] = np.where((vac.NAICS >= 100000) & (vac.NAICS < 400000), vac.jobs_lost, 0)
vac['service_closed'] = np.where(vac.NAICS >= 400000, vac.jobs_lost, 0)
vac['layoff'] = np.where(vac.close_layoff == 'Layoff', vac.jobs_lost, 0)
vac['closing'] = np.where(vac.close_layoff == 'Closing', vac.jobs_lost, 0)
vac.NAICS = vac.NAICS.astype(str)
vac1 = vac.groupby(by=['month', 'county']).sum().reset_index()
va = pd.merge(vaa1, vac1, how='outer', on=['month', 'county'])
va = va.sort_values(by=['month', 'county'])
va.jobs_added = va.jobs_added.fillna(0)
va.jobs_lost = va.jobs_lost.fillna(0)
va.agriculture_added = va.agriculture_added.fillna(0)
va.agriculture_closed = va.agriculture_closed.fillna(0)
va.manufacturing_added = va.manufacturing_added.fillna(0)
va.manufacturing_closed = va.manufacturing_closed.fillna(0)
va.service_added = va.service_added.fillna(0)
va.service_closed = va.service_closed.fillna(0)
va.new = va.new.fillna(0)
va.expansion = va.expansion.fillna(0)
va.layoff = va.layoff.fillna(0)
va.closing = va.closing.fillna(0)

In [41]:
df = pd.merge(va, vafips, left_on='county', right_on='name')
df = df[['month', 'code', 'jobs_added', 'jobs_lost', 'agriculture_added', 'manufacturing_added', 
         'service_added', 'agriculture_closed', 'manufacturing_closed', 'service_closed', 'new', 
         'expansion', 'layoff', 'closing']]
df = pd.merge(df, listing, how='right', left_on = ['code', 'month'], right_on = ['FIPS', 'date'])
df = df[['FIPS', 'date', 'price', 'prev_price_change', 'future_price_change', 'jobs_added', 'jobs_lost', 'agriculture_added',
       'manufacturing_added', 'service_added', 'agriculture_closed',
       'manufacturing_closed', 'service_closed', 'new', 'expansion', 'layoff',
       'closing']]
df.jobs_added = df.jobs_added.fillna(0)
df.jobs_lost = df.jobs_lost.fillna(0)
df.agriculture_added = df.agriculture_added.fillna(0)
df.agriculture_closed = df.agriculture_closed.fillna(0)
df.manufacturing_added = df.manufacturing_added.fillna(0)
df.manufacturing_closed = df.manufacturing_closed.fillna(0)
df.service_added = df.service_added.fillna(0)
df.service_closed = df.service_closed.fillna(0)
df.new = df.new.fillna(0)
df.expansion = df.expansion.fillna(0)
df.layoff = df.layoff.fillna(0)
df.closing = df.closing.fillna(0)
df2 = df[['FIPS', 'date', 'jobs_added', 'jobs_lost', 'new', 'expansion', 'layoff', 'closing', 'agriculture_added', 'manufacturing_added', 'service_added', 'agriculture_closed', 'manufacturing_closed', 'service_closed']]
df2['annual_jobs_added'] = df2.jobs_added.rolling(window=12).mean()
df2['quarterly_jobs_added'] = df2.jobs_added.rolling(window=3).sum()
df2['annual_agriculture_added'] = df2.agriculture_added.rolling(window=12).mean()
df2['annual_manufacturing_added'] = df2.manufacturing_added.rolling(window=12).mean()
df2['annual_service_added'] = df2.service_added.rolling(window=12).mean()
df2['annual_jobs_lost'] = df2.jobs_lost.rolling(window=12).mean()
df2['quarterly_jobs_lost'] = df2.jobs_lost.rolling(window=3).sum()
df2['annual_agriculture_closed'] = df2.agriculture_closed.rolling(window=12).mean()
df2['annual_manufacturing_closed'] = df2.manufacturing_closed.rolling(window=12).mean()
df2['annual_service_closed'] = df2.service_closed.rolling(window=12).mean()
df2['annual_new'] = df2.new.rolling(window=12).mean()
df2['quarterly_new'] = df2.new.rolling(window=3).sum()
df2['annual_expansion'] = df2.expansion.rolling(window=12).mean()
df2['quarterly_expansion'] = df2.expansion.rolling(window=3).sum()
df2['annual_layoff'] = df2.layoff.rolling(window=12).mean()
df2['quarterly_layoff'] = df2.layoff.rolling(window=3).sum()
df2['annual_closing'] = df2.closing.rolling(window=12).mean()
df2['quarterly_closing'] = df2.closing.rolling(window=3).sum()
df2 = df2[['FIPS', 'date', 'annual_jobs_added', 'annual_agriculture_added', 'annual_manufacturing_added', 'annual_service_added', 'annual_jobs_lost', 'annual_agriculture_closed', 'annual_manufacturing_closed', 'annual_service_closed', 'annual_new', 'annual_expansion', 'annual_layoff', 'annual_closing', 'quarterly_jobs_added', 'quarterly_jobs_lost', 'quarterly_new', 'quarterly_expansion', 'quarterly_layoff', 'quarterly_closing']]
df = pd.merge(df, df2, on=['FIPS', 'date'])
df = df.dropna()
df = pd.merge(df, unemp, left_on = ['FIPS', 'date'], right_on = ['series_id', 'date'])
df = df.drop('series_id', axis=1)
df = pd.merge(df, popul, left_on = ['date', 'FIPS'], right_on = ['date', 'FIPS'])
df = pd.merge(df, foreclose, left_on = ['date', 'FIPS'], right_on = ['date', 'FIPS'])
df = pd.merge(df, inventory, left_on = ['FIPS', 'date'], right_on = ['FIPS', 'month'])
df['inven_popul'] = df.popul/df.inven
df = pd.merge(df, inc_pc, left_on = ['FIPS', 'date'], right_on = ['FIPS', 'date'])
df = pd.merge(df, total_emp, left_on = ['FIPS', 'date'], right_on = ['FIPS', 'date'])
df = pd.merge(df, inf, left_on = 'date', right_on = 'timestamp')
df = df.dropna()
df

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,FIPS,date,price,prev_price_change,future_price_change,jobs_added,jobs_lost,agriculture_added,manufacturing_added,service_added,...,month,inven,inven_change,inven_popul,inc_pc,inc_pc_change,total_emp,emp_change,timestamp,inf_diff
0,51013,2011-04-01,519000.0,3.283582,0.192678,165.0,86.0,0.0,0.0,165.0,...,2011-04-01,742.0,-0.051151,282.194070,79415,1.166080,182675,50.852115,2011-04-01,0.025715
1,51041,2011-04-01,210000.0,-4.545455,-4.785714,772.0,0.0,0.0,0.0,772.0,...,2011-04-01,2717.0,-0.142632,116.755245,42249,0.243532,121294,36.252457,2011-04-01,0.025715
2,51085,2011-04-01,259900.0,-10.069204,-3.828396,20.0,0.0,0.0,20.0,0.0,...,2011-04-01,845.0,-0.117954,118.224852,44314,0.239171,47875,2.690072,2011-04-01,0.025715
3,51087,2011-04-01,188000.0,-10.454870,-1.861702,200.0,0.0,0.0,0.0,200.0,...,2011-04-01,2226.0,0.001350,138.108715,46785,-0.196327,180524,2.274693,2011-04-01,0.025715
4,51107,2011-04-01,449900.0,2.482916,5.556790,139.0,0.0,0.0,0.0,139.0,...,2011-04-01,2016.0,0.257642,156.547619,63218,1.157979,142560,28.868008,2011-04-01,0.025715
5,51179,2011-04-01,245000.0,-10.909091,22.040816,25.0,0.0,0.0,0.0,25.0,...,2011-04-01,834.0,0.293023,155.661871,46614,0.302868,39884,2.076994,2011-04-01,0.025715
6,51145,2011-04-01,269950.0,-10.001667,-5.732543,10.0,0.0,0.0,10.0,0.0,...,2011-04-01,282.0,0.160494,99.716312,39346,0.193786,6770,0.268028,2011-04-01,0.025715
7,51033,2011-04-01,154900.0,-7.245509,-3.227889,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,328.0,0.192727,87.320122,33670,0.145355,5685,0.593776,2011-04-01,0.025715
8,51043,2011-04-01,321450.0,2.047619,4.028620,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,104.0,-0.193798,134.721154,50221,-0.029640,4192,-0.971228,2011-04-01,0.025715
9,51047,2011-04-01,219900.0,-17.018868,9.095043,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,324.0,-0.169231,144.558642,36668,0.034125,15521,19.262402,2011-04-01,0.025715
10,51061,2011-04-01,349900.0,3.078509,8.573878,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,386.0,-0.074341,169.621762,55202,0.374210,22157,4.525436,2011-04-01,0.025715
11,51073,2011-04-01,265000.0,4.577743,-13.245283,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,546.0,0.392857,67.653846,39651,0.043036,9980,1.029693,2011-04-01,0.025715
12,51075,2011-04-01,396950.0,-6.047337,7.796952,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,176.0,-0.231441,123.573864,68224,0.423261,11866,0.172646,2011-04-01,0.025715
13,51101,2011-04-01,198000.0,1.538462,-9.116162,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,148.0,0.072464,108.094595,36294,-0.287948,3775,-0.698024,2011-04-01,0.025715
15,51127,2011-04-01,289995.0,-2.193929,-13.817480,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,235.0,0.358382,78.910638,54705,0.134488,3958,-0.044423,2011-04-01,0.025715
16,51157,2011-04-01,449700.0,14.719388,0.611519,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,70.0,0.590909,107.100000,48749,0.264598,1629,-0.881854,2011-04-01,0.025715
17,51187,2011-04-01,179900.0,-9.711418,-0.111173,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,368.0,0.076023,101.894022,36883,0.007402,12334,-0.224326,2011-04-01,0.025715
18,51550,2011-04-01,239900.0,-9.128788,10.462693,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,2297.0,-0.012468,97.326513,42067,-0.499673,101544,0.010167,2011-04-01,0.025715
19,51650,2011-04-01,166375.0,-12.388099,-1.487603,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,1254.0,0.152574,109.523923,35932,-0.260187,67488,-0.371784,2011-04-01,0.025715
20,51700,2011-04-01,179900.0,-5.265929,-10.586437,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,1456.0,0.116564,124.258929,35212,-0.164266,106398,0.640603,2011-04-01,0.025715
21,51710,2011-04-01,174900.0,-10.261673,0.057176,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,2104.0,0.162431,115.507129,34647,-0.168059,192685,0.777881,2011-04-01,0.025715
22,51740,2011-04-01,144900.0,-12.181818,-10.282954,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,1152.0,0.068646,82.855035,34683,-0.134958,50659,-0.734416,2011-04-01,0.025715
23,51800,2011-04-01,238000.0,-8.426318,-5.462185,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,968.0,-0.062924,87.623967,42244,0.007104,26521,-0.629848,2011-04-01,0.025715
24,51810,2011-04-01,245000.0,-5.769231,1.632653,0.0,0.0,0.0,0.0,0.0,...,2011-04-01,4000.0,-0.042604,109.730250,44595,-0.104140,193894,4.878248,2011-04-01,0.025715
25,51013,2011-05-01,510000.0,-1.912702,7.205882,241.0,0.0,0.0,0.0,241.0,...,2011-05-01,796.0,0.020513,263.050251,79415,1.166080,182675,50.852115,2011-05-01,0.021479
26,51087,2011-05-01,190000.0,-11.607351,-0.526316,85.0,50.0,0.0,23.0,62.0,...,2011-05-01,2090.0,-0.012754,147.095694,46785,-0.196327,180524,2.274693,2011-05-01,0.021479
27,51107,2011-05-01,458995.0,3.146103,4.554516,45.0,0.0,0.0,0.0,45.0,...,2011-05-01,2112.0,0.378590,149.431818,63218,1.157979,142560,28.868008,2011-05-01,0.021479
28,51187,2011-05-01,189900.0,0.184648,-6.793049,0.0,79.0,0.0,0.0,0.0,...,2011-05-01,378.0,0.038462,99.198413,36883,0.007402,12334,-0.224326,2011-05-01,0.021479
29,51033,2011-05-01,153950.0,-9.435849,3.864891,0.0,0.0,0.0,0.0,0.0,...,2011-05-01,342.0,0.315385,83.745614,33670,0.145355,5685,0.593776,2011-05-01,0.021479
30,51041,2011-05-01,214900.0,-4.446421,-5.076780,0.0,0.0,0.0,0.0,0.0,...,2011-05-01,2608.0,-0.126591,121.634969,42249,0.243532,121294,36.252457,2011-05-01,0.021479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,51700,2011-09-01,175000.0,-6.367041,-11.142857,0.0,0.0,0.0,0.0,0.0,...,2011-09-01,1383.0,-0.076769,130.249458,37310,0.059582,106089,-0.002904,2011-09-01,0.025113
2034,51710,2011-09-01,175000.0,-7.358391,2.285714,0.0,0.0,0.0,0.0,0.0,...,2011-09-01,1915.0,-0.063570,127.271540,35503,0.024706,190611,-0.010764,2011-09-01,0.025113
2035,51740,2011-09-01,139900.0,-12.012579,-2.930665,0.0,0.0,0.0,0.0,0.0,...,2011-09-01,1035.0,-0.088908,92.500483,36131,0.041750,51044,0.007600,2011-09-01,0.025113
2036,51800,2011-09-01,229900.0,-8.003201,2.174859,0.0,0.0,0.0,0.0,0.0,...,2011-09-01,914.0,-0.085085,92.728665,43856,0.038159,26673,0.005731,2011-09-01,0.025113
2037,51810,2011-09-01,249500.0,-0.200000,-4.208417,0.0,0.0,0.0,0.0,0.0,...,2011-09-01,3694.0,-0.153529,119.888468,46458,0.041776,193800,-0.000485,2011-09-01,0.025113
2038,51013,2015-08-01,549000.0,-5.181347,4.717668,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,712.0,0.174917,321.585674,86517,0.034744,188714,0.034038,2015-08-01,0.008840
2039,51033,2015-08-01,185000.0,2.834908,10.810811,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,217.0,0.043269,137.778802,41476,0.118374,6212,0.016528,2015-08-01,0.008840
2040,51041,2015-08-01,253250.0,7.313869,13.721619,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,1784.0,0.072115,187.920964,49350,0.054555,140734,0.052185,2015-08-01,0.008840
2041,51043,2015-08-01,385000.0,-3.508772,3.870130,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,155.0,0.115108,91.967742,58831,0.064237,4141,-0.027021,2015-08-01,0.008840
2042,51047,2015-08-01,291919.0,2.427719,11.640558,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,332.0,-0.072626,149.135542,42188,0.046797,16738,0.016395,2015-08-01,0.008840
2043,51061,2015-08-01,414990.0,-4.600000,7.231500,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,536.0,0.229358,127.695896,63780,0.059257,23711,0.018601,2015-08-01,0.008840
2044,51073,2015-08-01,259900.0,-3.202980,0.000000,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,504.0,-0.001980,73.410714,45397,0.050200,10098,-0.000594,2015-08-01,0.008840
2045,51075,2015-08-01,449000.0,5.647059,-2.227171,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,166.0,0.220588,133.487952,89158,0.085915,15902,0.061124,2015-08-01,0.008840
2046,51085,2015-08-01,305559.0,9.147705,4.709729,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,610.0,-0.006515,168.926230,55304,0.065362,53748,0.028080,2015-08-01,0.008840
2047,51087,2015-08-01,239990.0,5.745759,12.296346,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,1118.0,-0.017575,290.457961,59771,0.048007,200267,0.040197,2015-08-01,0.008840
2048,51101,2015-08-01,186825.0,1.590538,4.167001,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,142.0,-0.123457,114.654930,41169,0.066499,4010,0.054708,2015-08-01,0.008840
2049,51107,2015-08-01,519000.0,2.773804,1.156069,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,2126.0,0.030538,176.245061,70479,0.036151,166913,0.042197,2015-08-01,0.008840
2050,51115,2015-08-01,294999.0,-1.338127,-3.643741,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,204.0,-0.200000,43.377451,51016,0.040060,1606,0.010063,2015-08-01,0.008840
2051,51127,2015-08-01,305495.0,9.615657,-6.725151,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,241.0,0.075893,84.572614,67385,0.040342,4357,0.046852,2015-08-01,0.008840
2052,51145,2015-08-01,349475.0,12.752057,0.135918,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,185.0,-0.070352,151.594595,50055,0.083723,7651,-0.006622,2015-08-01,0.008840
2053,51157,2015-08-01,419900.0,-1.083628,-1.297928,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,110.0,0.122449,67.127273,57483,0.025292,1744,0.012188,2015-08-01,0.008840
2054,51179,2015-08-01,345000.0,-0.833573,1.420290,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,899.0,0.167532,156.719689,50717,0.034218,45205,0.016642,2015-08-01,0.008840
2055,51187,2015-08-01,224950.0,-0.022222,14.283174,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,352.0,0.023256,110.485795,42111,0.042790,12937,-0.028097,2015-08-01,0.008840
2056,51550,2015-08-01,279900.0,-0.035714,12.540193,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,1755.0,-0.009034,134.012536,46965,0.042046,104873,0.020294,2015-08-01,0.008840
2057,51650,2015-08-01,169900.0,1.161060,-0.529723,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,1040.0,0.105207,131.053846,40636,0.042858,64305,-0.007578,2015-08-01,0.008840
2058,51700,2015-08-01,180000.0,5.944673,-5.555556,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,967.0,-0.005144,187.262668,40648,0.045070,108280,-0.005118,2015-08-01,0.008840
2059,51710,2015-08-01,197500.0,4.002106,1.215190,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,1568.0,-0.026087,157.112245,38629,0.034078,190758,0.017316,2015-08-01,0.008840
2060,51740,2015-08-01,145950.0,4.250000,2.774923,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,910.0,0.115196,105.759341,38766,0.038746,53219,0.011153,2015-08-01,0.008840
2061,51800,2015-08-01,272400.0,2.792453,0.917768,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,857.0,-0.041387,102.803967,48003,0.045384,30582,0.044218,2015-08-01,0.008840
2062,51810,2015-08-01,279816.0,3.635556,1.852646,0.0,0.0,0.0,0.0,0.0,...,2015-08-01,2926.0,0.013158,154.088859,52843,0.048868,202134,0.014515,2015-08-01,0.008840

In [42]:
y = df.future_price_change
X = df[['new', 'expansion', 'layoff', 'closing', 'annual_new', 'annual_expansion', 'annual_layoff', 'annual_closing', 'unemp_rate', 'annual_unemp_change', 'annual_popul_change', 'foreclose_rate', 'inven', 'inven_change', 'inven_popul', 'emp_change', 'inc_pc_change', 'inc_pc', 'inf_diff', 'prev_price_change', 'quarterly_new', 'quarterly_expansion', 'quarterly_layoff', 'quarterly_closing']]

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [44]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)
y_pred_reg = reg.predict(X_test)
reg.score(X_test, y_test)

0.09096684723649917

In [50]:
from sklearn.ensemble import GradientBoostingRegressor
gbrt = GradientBoostingRegressor().fit(X_train, y_train)
y_test_pred_gb = gbrt.predict(X_test)
y_train_pred_gb = gbrt.predict(X_train)
gbrt.score(X_test, y_test)

0.4849538896830074

In [51]:
from sklearn.ensemble import RandomForestRegressor
rfrt = RandomForestRegressor().fit(X_train, y_train)
y_test_pred_rf = rfrt.predict(X_test)
y_train_pred_rf = rfrt.predict(X_train)
rfrt.score(X_test, y_test)

0.5561098981368626

In [47]:
import statsmodels.api as sm
mod = sm.OLS(y, X)
res = mod.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
===============================================================================
Dep. Variable:     future_price_change   R-squared:                       0.335
Model:                             OLS   Adj. R-squared:                  0.327
Method:                  Least Squares   F-statistic:                     42.73
Date:                 Sun, 09 Dec 2018   Prob (F-statistic):          9.85e-161
Time:                         17:17:12   Log-Likelihood:                -6522.5
No. Observations:                 2057   AIC:                         1.309e+04
Df Residuals:                     2033   BIC:                         1.323e+04
Df Model:                           24
Covariance Type:             nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
new                     0.0056      0.003      1.601      0.110      -0.001       0.012
expansion              -0.0016      0.002     -0.650      0.515      -0.006       0.003
layoff                 -0.0043      0.024     -0.180      0.857      -0.051       0.043
closing                -0.0063      0.015     -0.412      0.681      -0.036       0.024
annual_new             -0.0178      0.011     -1.571      0.116      -0.040       0.004
annual_expansion       -0.0038      0.007     -0.543      0.587      -0.017       0.010
annual_layoff          -0.0431      0.077     -0.563      0.574      -0.193       0.107
annual_closing          0.0886      0.039      2.280      0.023       0.012       0.165
unemp_rate             -0.0037      0.082     -0.045      0.964      -0.165       0.158
annual_unemp_change    -1.6062      0.354     -4.535      0.000      -2.301      -0.912
annual_popul_change    -0.5417      0.100     -5.407      0.000      -0.738      -0.345
foreclose_rate         -0.0534      0.059     -0.898      0.369      -0.170       0.063
inven                   0.0002      0.000      1.186      0.236      -0.000       0.001
inven_change           -4.8591      0.715     -6.791      0.000      -6.262      -3.456
inven_popul             0.0138      0.002      7.589      0.000       0.010       0.017
emp_change              0.1228      0.078      1.569      0.117      -0.031       0.276
inc_pc_change           1.8179      1.939      0.937      0.349      -1.986       5.621
inc_pc               2.879e-05   8.44e-06      3.409      0.001    1.22e-05    4.53e-05
inf_diff              -65.6173     19.528     -3.360      0.001    -103.915     -27.320
prev_price_change      -0.1490      0.020     -7.352      0.000      -0.189      -0.109
quarterly_new          -0.0007      0.002     -0.285      0.776      -0.005       0.004
quarterly_expansion     0.0021      0.002      1.309      0.191      -0.001       0.005
quarterly_layoff        0.0244      0.015      1.580      0.114      -0.006       0.055
quarterly_closing       0.0027      0.010      0.276      0.782      -0.016       0.022
==============================================================================
Omnibus:                       53.497   Durbin-Watson:                   1.749
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              110.904
Skew:                           0.132   Prob(JB):                     8.27e-25
Kurtosis:                       4.107   Cond. No.                     7.96e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.96e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [52]:
gbrt_feature_importances = pd.DataFrame(gbrt.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', ascending=False)
gbrt_feature_importances.sort_values

<bound method DataFrame.sort_values of                      importance
prev_price_change      0.144890
inven_popul            0.136194
inc_pc                 0.119765
inven_change           0.092596
emp_change             0.089733
inven                  0.082857
inc_pc_change          0.071443
annual_popul_change    0.063190
unemp_rate             0.055391
inf_diff               0.045864
foreclose_rate         0.031235
annual_unemp_change    0.019219
annual_expansion       0.016897
new                    0.014608
expansion              0.007478
quarterly_expansion    0.003581
annual_new             0.002800
quarterly_new          0.002174
layoff                 0.000084
annual_closing         0.000000
annual_layoff          0.000000
closing                0.000000
quarterly_layoff       0.000000
quarterly_closing      0.000000>

In [53]:
rfrt_feature_importances = pd.DataFrame(rfrt.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', ascending=False)
rfrt_feature_importances.sort_values

<bound method DataFrame.sort_values of                      importance
inven_popul            0.163023
emp_change             0.139470
prev_price_change      0.132339
inc_pc_change          0.088187
inven_change           0.082268
inven                  0.075916
unemp_rate             0.055852
annual_popul_change    0.053426
inf_diff               0.050352
foreclose_rate         0.050069
inc_pc                 0.046848
annual_unemp_change    0.032272
annual_expansion       0.007299
annual_new             0.005835
quarterly_expansion    0.005203
expansion              0.003350
quarterly_new          0.003055
annual_closing         0.002171
new                    0.002162
annual_layoff          0.000329
quarterly_closing      0.000322
closing                0.000176
quarterly_layoff       0.000080
layoff                 0.000000>

In [ ]:
y = df.price_change
X = df[['jobs_added', 'jobs_lost', 'annual_jobs_added', 'annual_jobs_lost', 'annual_manufacturing_added', 'annual_service_added', 'annual_service_closed', 'unemp_rate', 'annual_unemp_change', 'annual_popul_change', 'foreclose_rate', 'foreclose_rate_change', 'inven', 'inven_change', 'inven_popul', 'emp_change', 'inc_pc_change', 'inc_pc', 'inf_diff']]

In [ ]:
X_test
x1 = [0, 0, 0, 0, 0, 0, 0, 6.6, -1.3, -0.5, 11.8, ]